export const izvodaci = [
    { sifra: 1, dominantniZanr: 1, naziv: 'Led Zeppelin' },
    { sifra: 2, dominantniZanr: 1, naziv: 'The Doors' },
    { sifra: 3, dominantniZanr: 1, naziv: 'The Rolling Stones' },
    { sifra: 4, dominantniZanr: 1, naziv: 'Creedence Clearwater Revival' },
    { sifra: 5, dominantniZanr: 1, naziv: 'Cream' },
    { sifra: 6, dominantniZanr: 6, naziv: 'Iron Maiden' },
    { sifra: 7, dominantniZanr: 6, naziv: 'Black Sabbath' },
    { sifra: 8, dominantniZanr: 11, naziv: 'The Cult' },
    { sifra: 10, dominantniZanr: 2, naziv: 'Linkin Park' },
    { sifra: 14, dominantniZanr: 3, naziv: 'Green Day' },
    { sifra: 17, dominantniZanr: 4, naziv: 'ABBA' },
    { sifra: 21, dominantniZanr: 5, naziv: 'Mišo Kovač' },
    { sifra: 26, dominantniZanr: 7, naziv: 'Oliver Dragojević' },
    { sifra: 31, dominantniZanr: 10, naziv: 'Ace of Base' },
    { sifra: 32, dominantniZanr: 13, naziv: 'Depeche Mode' },
    { sifra: 35, dominantniZanr: 1, naziv: 'Tina Turner' },
    { sifra: 40, dominantniZanr: 4, naziv: 'Laura Branigan' },
    { sifra: 41, dominantniZanr: 11, naziv: 'Bijelo Dugme' },
    { sifra: 44, dominantniZanr: 14, naziv: 'Kim Carnes' },
    { sifra: 45, dominantniZanr: 1, naziv: 'Billy Idol' }, 
    { sifra: 46, dominantniZanr: 4, naziv: 'Modern Talking' }, 
    { sifra: 49, dominantniZanr: 4, naziv: 'Madonna' },
    { sifra: 50, dominantniZanr: 9, naziv: 'Gigi D\'Agostino' }, 
    { sifra: 54, dominantniZanr: 13, naziv: 'Kavinsky' }, 
    { sifra: 55, dominantniZanr: 4, naziv: 'Rihanna' },
    { sifra: 57, dominantniZanr: 4, naziv: 'Lady Gaga' },
    { sifra: 59, dominantniZanr: 4, naziv: 'Kesha' },
    { sifra: 61, dominantniZanr: 9, naziv: 'NBSPLV' }, 
    { sifra: 64, dominantniZanr: 10, naziv: 'Bob Marley & The Wailers' }, 
    { sifra: 69, dominantniZanr: 9, naziv: 'MGMT' }, 
    { sifra: 72, dominantniZanr: 9, naziv: 'Crystal Castles' },
    { sifra: 76, dominantniZanr: 9, naziv: 'Basshunter' },
    { sifra: 80, dominantniZanr: 1, naziv: 'Chuck Berry' }, 
    { sifra: 84, dominantniZanr: 1, naziv: 'Roy Orbison' },
    { sifra: 85, dominantniZanr: 1, naziv: 'Ritchie Valens' },
    { sifra: 86, dominantniZanr: 4, naziv: 'Paul Anka' },
    { sifra: 87, dominantniZanr: 12, naziv: 'Frank Sinatra' }, 
    { sifra: 88, dominantniZanr: 8, naziv: 'John Denver' }, 
    { sifra: 89, dominantniZanr: 8, naziv: 'The Highwaymen' }, 
    { sifra: 90, dominantniZanr: 8, naziv: 'Johnny Cash' },
    { sifra: 91, dominantniZanr: 8, naziv: 'Waylon Jennings & Willie Nelson' },
    { sifra: 92, dominantniZanr: 8, naziv: 'Juice Newton' },
    { sifra: 93, dominantniZanr: 8, naziv: 'Conway Twitty & Loretta Lynn' },
    { sifra: 94, dominantniZanr: 8, naziv: 'Merle Haggard' },
    { sifra: 95, dominantniZanr: 8, naziv: 'George Strait' },
    { sifra: 96, dominantniZanr: 8, naziv: 'Asleep at the Wheel' }, 
    { sifra: 97, dominantniZanr: 8, naziv: 'Patsy Cline' },
    { sifra: 98, dominantniZanr: 8, naziv: 'Mickey Gilley' },
    { sifra: 99, dominantniZanr: 8, naziv: 'Eddie Rabbitt' },
    { sifra: 100, dominantniZanr: 8, naziv: 'Country Family' }
];