export const izvodaci = [
    { sifra: 1, dominantniZanr: 1, naziv: 'Led Zeppelin' },
    { sifra: 2, dominantniZanr: 7,naziv: 'The Doors' },
    { sifra: 3, dominantniZanr: 1,naziv: 'The Rolling Stones' },
    { sifra: 4, dominantniZanr: 1,naziv: 'Creedence Clearwater Revival' },
    { sifra: 5, dominantniZanr: 1,naziv: 'Cream' },
    { sifra: 6, dominantniZanr: 1,naziv: 'Iron Maiden' },
    { sifra: 7, dominantniZanr: 1,naziv: 'Black Sabbath' },
    { sifra: 8, dominantniZanr: 1,naziv: 'The Cult' },
    { sifra: 10, dominantniZanr: 1,naziv: 'Linkin Park' },
    { sifra: 14, dominantniZanr: 1,naziv: 'Green Day' },
    { sifra: 17, dominantniZanr: 1,naziv: 'ABBA' },
    { sifra: 21, dominantniZanr: 1,naziv: 'Mišo Kovač' },
    { sifra: 26, dominantniZanr: 1,naziv: 'Oliver Dragojević' },
    { sifra: 31, dominantniZanr: 1,naziv: 'Ace of Base' },
    { sifra: 32, dominantniZanr: 1,naziv: 'Depeche Mode' },
    { sifra: 35, dominantniZanr: 1,naziv: 'Tina Turner' },
    { sifra: 40, dominantniZanr: 1,naziv: 'Laura Branigan' },
    { sifra: 41, dominantniZanr: 1,naziv: 'Bijelo Dugme' },
    { sifra: 44, dominantniZanr: 1,naziv: 'Kim Carnes' },
    { sifra: 45, dominantniZanr: 1,naziv: 'Billy Idol' },
    { sifra: 46, dominantniZanr: 1,naziv: 'Modern Talking' },
    { sifra: 49, naziv: 'Madonna' },
    { sifra: 50, naziv: 'Gigi D\'Agostino' },
    { sifra: 54, naziv: 'Kavinsky' },
    { sifra: 55, naziv: 'Rihanna' },
    { sifra: 57, naziv: 'Lady Gaga' },
    { sifra: 59, naziv: 'Kesha' },
    { sifra: 61, naziv: 'NBSPLV' },
    { sifra: 64, naziv: 'Bob Marley & The Wailers' },
    { sifra: 69, naziv: 'MGMT' },
    { sifra: 72, naziv: 'Crystal Castles' },
    { sifra: 76, naziv: 'Basshunter' },
    { sifra: 80, naziv: 'Chuck Berry' },
    { sifra: 84, naziv: 'Roy Orbison' },
    { sifra: 85, naziv: 'Ritchie Valens' },
    { sifra: 86, naziv: 'Paul Anka' },
    { sifra: 87, naziv: 'Frank Sinatra' },
    { sifra: 88, naziv: 'John Denver' },
    { sifra: 89, naziv: 'The Highwaymen' },
    { sifra: 90, naziv: 'Johnny Cash' },
    { sifra: 91, naziv: 'Waylon Jennings & Willie Nelson' },
    { sifra: 92, naziv: 'Juice Newton' },
    { sifra: 93, naziv: 'Conway Twitty & Loretta Lynn' },
    { sifra: 94, naziv: 'Merle Haggard' },
    { sifra: 95, naziv: 'George Strait' },
    { sifra: 96, naziv: 'Asleep at the Wheel' },
    { sifra: 97, naziv: 'Patsy Cline' },
    { sifra: 98, naziv: 'Mickey Gilley' },
    { sifra: 99, naziv: 'Eddie Rabbitt' },
    { sifra: 100, naziv: 'Country Family' }
];