export const pjesme = [
    { sifra: 1, album: 1, naziv: 'Stairway to Heaven', zanr: 1, trajanje: 482 },
    { sifra: 2, album: 2, naziv: 'Riders on the Storm', zanr: 1, trajanje: 434 },
    { sifra: 3, album: 3, naziv: 'Gimme Shelter', zanr: 1, trajanje: 270 },
    { sifra: 4, album: 4, naziv: 'Have You Ever Seen the Rain', zanr: 1, trajanje: 159 },
    { sifra: 5, album: 5, naziv: 'Fire Woman', zanr: 1, trajanje: 311 },
    { sifra: 6, album: 6, naziv: 'In the End', zanr: 2, trajanje: 216 },
    { sifra: 7, album: 7, naziv: 'Numb', zanr: 2, trajanje: 187 },
    { sifra: 8, album: 8, naziv: 'What I\'ve Done', zanr: 2, trajanje: 205 },
    { sifra: 9, album: 9, naziv: 'Boulevard of Broken Dreams', zanr: 3, trajanje: 260 },
    { sifra: 10, album: 10, naziv: 'Dancing Queen', zanr: 4, trajanje: 231 },
    { sifra: 11, album: 11, naziv: 'SOS', zanr: 4, trajanje: 202 },
    { sifra: 12, album: 12, naziv: 'Chiquitita', zanr: 4, trajanje: 326 },
    { sifra: 13, album: 13, naziv: 'The Winner Takes It All', zanr: 4, trajanje: 296 },
    { sifra: 14, album: 14, naziv: 'Proplakat će zora', zanr: 5, trajanje: 213 },
    { sifra: 15, album: 15, naziv: 'Ti si pjesma moje duše', zanr: 5, trajanje: 240 },
    { sifra: 16, album: 16, naziv: 'Svi pjevaju, ja ne čujem', zanr: 5, trajanje: 248 },
    { sifra: 17, album: 17, naziv: 'Ljubavna pjesma', zanr: 5, trajanje: 215 },
    { sifra: 18, album: 18, naziv: 'Poeta', zanr: 5, trajanje: 218 },
    { sifra: 19, album: 19, naziv: 'Trag u beskraju', zanr: 5, trajanje: 275 },
    { sifra: 20, album: 20, naziv: 'Enjoy the Silence', zanr: 9, trajanje: 256 },
    { sifra: 21, album: 21, naziv: 'What\'s Love Got to Do with It', zanr: 4, trajanje: 228 },
    { sifra: 22, album: 22, naziv: 'The Best', zanr: 4, trajanje: 328 },
    { sifra: 23, album: 23, naziv: 'Self Control', zanr: 4, trajanje: 248 },
    { sifra: 24, album: 24, naziv: 'Lipe cvatu', zanr: 1, trajanje: 240 },
    { sifra: 25, album: 25, naziv: 'Bette Davis Eyes', zanr: 4, trajanje: 227 },
    { sifra: 26, album: 26, naziv: 'You\'re My Heart, You\'re My Soul', zanr: 4, trajanje: 228 },
    { sifra: 27, album: 27, naziv: 'Bla Bla Bla', zanr: 9, trajanje: 195 },
    { sifra: 28, album: 28, naziv: 'Umbrella', zanr: 4, trajanje: 275 },
    { sifra: 29, album: 29, naziv: 'Bad Romance', zanr: 4, trajanje: 294 },
    { sifra: 30, album: 30, naziv: 'Jamming', zanr: 10, trajanje: 211 },
    { sifra: 31, album: 31, naziv: 'Kids', zanr: 9, trajanje: 302 },
    { sifra: 32, album: 32, naziv: 'My Way', zanr: 4, trajanje: 275 },
    { sifra: 33, album: 33, naziv: 'Ring of Fire', zanr: 8, trajanje: 157 }
];